import React,{useEffect,useMemo,useState} from 'react';
import {RefreshCw,PlugZap,CheckCircle2,Clock3,Database,ExternalLink,AlertTriangle,Wifi,ShieldCheck,ChevronDown,ChevronUp} from 'lucide-react';
const C={surface:'#fff',border:'#DBDFD4',ink:'#1B231C',soft:'#586055',faint:'#8A9184',primary:'#2F5C48',tint:'#E4EDE6',high:'#AC2B22',highTint:'#F8E6E3',med:'#95600A'};
const Card=({children,style={},className=''})=><div className={`bd-card ${className}`} style={{background:C.surface,border:`1px solid ${C.border}`,borderRadius:10,...style}}>{children}</div>;
function Badge({kind='neutral',children}){return <span className={`bd-status-badge ${kind}`}>{children}</span>}
function stateFor(c){const latest=c.latest;if(!latest)return {kind:'warn',label:'NOT SYNCED',detail:'No persisted snapshot captured'};if(latest.ok)return {kind:'ok',label:'SNAPSHOT OK',detail:`HTTP ${latest.httpStatus||200} · ${new Date(latest.fetchedAt||latest.createdAt).toLocaleString()}`};return {kind:'bad',label:'SYNC FAILED',detail:`HTTP ${latest.httpStatus||'—'} · ${latest.errorMessage||'Last attempt failed'}`};}
async function readJson(r){const text=await r.text();let body={};try{body=text?JSON.parse(text):{};}catch{body={error:text||`Request failed with HTTP ${r.status}.`};}return {body,text};}
export default function IntegrationControlPage({canAdmin=false}){
 const [connectors,setConnectors]=useState([]),[runs,setRuns]=useState([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState({}),[error,setError]=useState(''),[message,setMessage]=useState(''),[expanded,setExpanded]=useState({}),[snapshotHistory,setSnapshotHistory]=useState({});
 const load=async()=>{setLoading(true);setError('');try{const [a,b]=await Promise.all([fetch('/api/source-connectors/catalog',{credentials:'include',cache:'no-store'}),fetch('/api/data-ingestion/runs?limit=30',{credentials:'include',cache:'no-store'})]);const aj=await readJson(a),bj=await readJson(b);if(!a.ok)throw new Error(aj.body.error||`Connector catalog failed (HTTP ${a.status}).`);if(!b.ok)throw new Error(bj.body.error||`Intake ledger failed (HTTP ${b.status}).`);setConnectors(aj.body.connectors||[]);setRuns(bj.body.runs||[])}catch(e){setError(e.message||'Integration control unavailable.')}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const successfulSnapshots=useMemo(()=>connectors.filter(x=>x.latest?.ok).length,[connectors]);
 const loadSnapshots=async(id)=>{const key=`snapshots:${id}`;setBusy(s=>({...s,[key]:true}));setError('');try{const r=await fetch(`/api/source-connectors/${encodeURIComponent(id)}/snapshots?limit=10`,{credentials:'include',cache:'no-store'});const j=await readJson(r);if(!r.ok)throw new Error(j.body.error||`Snapshots failed (HTTP ${r.status}).`);setSnapshotHistory(s=>({...s,[id]:j.body.snapshots||[]}));setExpanded(s=>({...s,[id]:true}));}catch(e){setError(e.message||'Unable to load connector snapshots.')}finally{setBusy(s=>({...s,[key]:false}))}};
 const bulkSync=async()=>{if(!canAdmin){setError('Administrator governance permission is required for bulk snapshot capture.');return;}setBusy(s=>({...s,bulkSync:true}));setError('');setMessage('');try{const r=await fetch('/api/source-connectors/bulk-sync',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({})});const j=await readJson(r);if(!r.ok)throw new Error(j.body.error||`Bulk snapshot failed (HTTP ${r.status}).`);const ok=(j.body.results||[]).filter(x=>x.status==='SNAPSHOT_OK').length;setMessage(`Bulk source snapshot run complete: ${ok}/${j.body.count||0} snapshots captured. Public-source evidence remains non-authoritative.`);await load();}catch(e){setError(e.message||'Bulk snapshot run failed safely.')}finally{setBusy(s=>({...s,bulkSync:false}))}};
 const action=async(id,mode)=>{if(!canAdmin){setError('Administrator governance permission is required for connector checks and snapshot capture.');return;}const key=`${mode}:${id}`;setBusy(s=>({...s,[key]:true}));setMessage('');setError('');try{const options={method:mode==='check'?'GET':'POST',credentials:'include',cache:'no-store'};if(mode!=='check')options.headers={'Content-Type':'application/json'},options.body='{}';const r=await fetch(`/api/source-connectors/${encodeURIComponent(id)}/${mode==='check'?'check':'sync'}`,options);const j=await readJson(r);if(!r.ok)throw new Error(j.body.error||`${mode==='check'?'Connection check':'Snapshot capture'} failed (HTTP ${r.status}).`);const snap=j.body.snapshot||{};const status=snap.httpStatus?`HTTP ${snap.httpStatus}`:'request completed';setMessage(`${j.body.connector?.name||id}: ${mode==='check'?'source reachable':'snapshot captured'} · ${status}. ${j.body.note||'Public-source evidence remains non-authoritative.'}`);if(mode!=='check')await load();}catch(e){setError(e.message||`${mode==='check'?'Connection check':'Snapshot capture'} failed safely.`)}finally{setBusy(s=>({...s,[key]:false}))}};
 return <div className="bd-page" style={{fontFamily:"'IBM Plex Sans','Inter',system-ui,sans-serif",display:'flex',flexDirection:'column',gap:14}}>
  <div className="bd-page-header"><div className="bd-page-header-copy"><div style={{fontSize:10.5,color:C.faint,textTransform:'uppercase',letterSpacing:.7}}>Authorised integrations</div><h2 className="bd-page-title">Integration Control Center</h2><div className="bd-page-subtitle">Test source reachability, capture public snapshots and review intake runs. A public snapshot never becomes an authoritative government project record automatically.</div></div><div className="bd-page-actions"><button className="bd-small-action primary" onClick={load} disabled={loading}><RefreshCw size={14}/>{loading?'Refreshing…':'Refresh'}</button><button className="bd-small-action primary" onClick={bulkSync} disabled={!canAdmin||busy.bulkSync}><Database size={14}/>{busy.bulkSync?'Syncing…':'Bulk snapshot'}</button></div></div>
  {error&&<Card style={{padding:12,background:C.highTint,color:C.high,fontSize:12,lineHeight:1.45}}><AlertTriangle size={14} style={{verticalAlign:'-2px',marginRight:6}}/>{error}</Card>}
  {!canAdmin&&<Card style={{padding:11,background:'#F3ECDB',border:`1px solid ${C.gold}33`,color:C.soft,fontSize:11.5,lineHeight:1.45}}><ShieldCheck size={14} color={C.gold} style={{verticalAlign:'-2px',marginRight:6}}/>Connector reachability checks and snapshot capture are administrator-governed. Source links and persisted history remain available for inspection.</Card>}
  {message&&<Card style={{padding:12,background:C.tint,color:C.primary,fontSize:12,lineHeight:1.45}}><CheckCircle2 size={14} style={{verticalAlign:'-2px',marginRight:6}}/>{message}</Card>}
  <div className="bd-responsive-three"><Card style={{padding:14}}><div style={{fontSize:10.5,color:C.faint,textTransform:'uppercase'}}>Catalog connectors</div><div style={{fontSize:27,fontWeight:750,color:C.ink,marginTop:4}}>{connectors.length}</div><div className="bd-inline-note">Configured source definitions</div></Card><Card style={{padding:14}}><div style={{fontSize:10.5,color:C.faint,textTransform:'uppercase'}}>Successful snapshots</div><div style={{fontSize:27,fontWeight:750,color:C.primary,marginTop:4}}>{successfulSnapshots}</div><div className="bd-inline-note">Persisted public-source evidence</div></Card><Card style={{padding:14}}><div style={{fontSize:10.5,color:C.faint,textTransform:'uppercase'}}>Recent intake runs</div><div style={{fontSize:27,fontWeight:750,color:C.ink,marginTop:4}}>{runs.length}</div><div className="bd-inline-note">Uploaded dataset intake records</div></Card></div>
  <Card style={{padding:16}}><div style={{display:'flex',alignItems:'center',gap:8}}><PlugZap size={18} color={C.primary}/><div><div style={{fontSize:10.5,color:C.faint,textTransform:'uppercase'}}>Connector registry</div><div style={{fontSize:18,fontWeight:750,color:C.ink}}>Public and authorised source controls</div></div></div>
   <div style={{display:'grid',gap:8,marginTop:12}}>{connectors.map(c=>{const s=stateFor(c);const checking=Boolean(busy[`check:${c.id}`]);const syncing=Boolean(busy[`sync:${c.id}`]);return <div key={c.id} className="bd-connector-row" style={{padding:'11px 12px',border:`1px solid ${C.border}`,borderRadius:8}}><div className="bd-safe-text"><div style={{fontWeight:700,fontSize:12.5,color:C.ink,lineHeight:1.3}}>{c.name||c.id}</div><div style={{fontSize:10.8,color:C.faint,marginTop:3,lineHeight:1.35}}>{c.owner} · {c.scope}</div></div><div><Badge kind="neutral">{c.accessMode||'PUBLIC'}</Badge></div><div className="bd-safe-text"><Badge kind={s.kind}>{s.label}</Badge><div className="bd-inline-note" style={{marginTop:4}}>{s.detail}</div></div><div className="bd-connector-actions"><a className="bd-small-action" href={c.url} target="_blank" rel="noreferrer"><ExternalLink size={13}/>Source</a><button className="bd-small-action" onClick={()=>action(c.id,'check')} disabled={!canAdmin||checking||syncing} title={canAdmin?'Test source reachability':'Administrator governance permission required'}>{checking?<><RefreshCw size={13}/>Testing…</>:<><Wifi size={13}/>{canAdmin?'Test source':'Test · Admin'}</>}</button><button className="bd-small-action primary" onClick={()=>action(c.id,'sync')} disabled={!canAdmin||checking||syncing} title={canAdmin?'Capture public-source snapshot':'Administrator governance permission required'}>{syncing?<><RefreshCw size={13}/>Capturing…</>:<><RefreshCw size={13}/>{canAdmin?'Capture snapshot':'Capture · Admin'}</>}</button><button className="bd-small-action" onClick={()=>expanded[c.id]?setExpanded(s=>({...s,[c.id]:false})):loadSnapshots(c.id)} disabled={Boolean(busy[`snapshots:${c.id}`])}>{busy[`snapshots:${c.id}`]?<><RefreshCw size={13}/>Loading…</>:expanded[c.id]?<><ChevronUp size={13}/>Hide history</>:<><ChevronDown size={13}/>History</>}</button></div>{expanded[c.id]&&<div style={{marginTop:9,padding:'8px 10px',background:'#FAFBF8',borderTop:`1px solid ${C.border}`,display:'grid',gap:6}}>{(snapshotHistory[c.id]||[]).map(snap=><div key={snap.id} style={{display:'grid',gridTemplateColumns:'auto 1fr auto',gap:8,alignItems:'center',fontSize:10.5}}><Badge kind={snap.ok?'ok':'bad'}>{snap.ok?'OK':snap.status||'ERROR'}</Badge><span className='bd-safe-text'>{snap.fetchedAt?new Date(snap.fetchedAt).toLocaleString():'—'} · SHA {String(snap.bodySha256||'').slice(0,14)}…</span><span>{snap.httpStatus??'—'}</span></div>)}{!(snapshotHistory[c.id]||[]).length&&<div className='bd-inline-note'>No persisted snapshots for this connector.</div>}</div>}</div>})}</div>
   <div className="bd-inline-note" style={{marginTop:10}}>Test source performs a live reachability check without persistence. Capture snapshot persists the HTTP result, timestamp, SHA-256 and parser output. Both require the existing workflow-admin permission.</div>
  </Card>
  <Card style={{padding:16}}><div style={{display:'flex',alignItems:'center',gap:8}}><Database size={18} color={C.primary}/><div><div style={{fontSize:10.5,color:C.faint,textTransform:'uppercase'}}>Recent data intake</div><div style={{fontSize:18,fontWeight:750,color:C.ink}}>Dataset intake ledger</div></div></div><div style={{display:'grid',gap:7,marginTop:12}}>{runs.slice(0,8).map(r=><div key={r.id} style={{display:'grid',gridTemplateColumns:'minmax(0,1fr) auto',gap:10,alignItems:'center',padding:'9px 11px',border:`1px solid ${C.border}`,borderRadius:8}}><div className="bd-safe-text"><div style={{fontWeight:650,color:C.ink,fontSize:11.5}}>{r.originalFilename||r.filename||r.id}</div><div className="bd-inline-note">{r.sourceClassification||'UNCLASSIFIED'}{r.createdAt?` · ${new Date(r.createdAt).toLocaleString()}`:''}</div></div><span style={{display:'inline-flex',alignItems:'center',gap:5,color:r.status==='ANALYZED'?C.primary:C.med,fontSize:10.5,fontWeight:750}}>{r.status==='ANALYZED'?<CheckCircle2 size={14}/>:<Clock3 size={14}/>} {r.status||'UNKNOWN'}</span></div>)}{!runs.length&&<div style={{padding:18,textAlign:'center',color:C.faint,fontSize:12}}>No intake runs recorded yet. Upload a dataset from Data Integration to create a forensic intake record.</div>}</div></Card>
  <Card style={{padding:12,background:'#F7F8F4'}}><div style={{display:'flex',gap:8,alignItems:'flex-start',fontSize:11.5,color:C.soft,lineHeight:1.5}}><ShieldCheck size={15} color={C.primary}/><div><b style={{color:C.ink}}>Trust boundary:</b> these controls verify or capture public web evidence only. They do not claim official API access, write to government systems, or promote source data into production ML.</div></div></Card>
 </div>
}
