import React,{useEffect,useMemo,useState} from 'react';
import {Activity,AlertTriangle,BarChart3,Database,Download,RefreshCw,ShieldCheck,Target,TrendingUp} from 'lucide-react';

const C={surface:'#fff',border:'#DBDFD4',ink:'#1B231C',soft:'#586055',faint:'#8A9184',primary:'#2F5C48',tint:'#E4EDE6',high:'#AC2B22',highTint:'#F8E6E3',med:'#95600A',medTint:'#F7EDD9'};
const FONT="'IBM Plex Sans','Inter',system-ui,sans-serif";
function Card({children,style={}}){return <div style={{background:C.surface,border:`1px solid ${C.border}`,borderRadius:10,...style}}>{children}</div>}
function Metric({label,value,icon:Icon,sub}){return <Card style={{padding:14}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><span style={{fontSize:11,color:C.faint}}>{label}</span>{Icon&&<Icon size={15} color={C.primary}/>}</div><div style={{marginTop:6,fontSize:22,fontWeight:800,color:C.ink}}>{value}</div>{sub&&<div style={{marginTop:3,fontSize:10.5,color:C.faint}}>{sub}</div>}</Card>}
export default function NationalIntelligencePage({onOpenProject}){
 const [data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[selectedStage,setSelectedStage]=useState(null);
 const refresh=async()=>{setLoading(true);setError('');try{const r=await fetch('/api/portfolio/intelligence',{credentials:'include'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Portfolio intelligence unavailable.');setData(j);}catch(e){setError(e?.message||'Portfolio intelligence unavailable.');}finally{setLoading(false);}};
 useEffect(()=>{refresh();const t=setInterval(()=>{if(document.visibilityState==='visible')refresh();},60000);return()=>clearInterval(t);},[]);
 const exportCsv=()=>{window.location.href='/api/portfolio/export.csv';};
 const top=data?.interventionQueue||[];
 return <div style={{fontFamily:FONT,display:'flex',flexDirection:'column',gap:14}}>
  <div style={{display:'flex',justifyContent:'space-between',alignItems:'flex-end',gap:12,flexWrap:'wrap'}}><div><div style={{fontSize:11,color:C.faint,textTransform:'uppercase',letterSpacing:.7}}>BhoomiDrishti intelligence layer</div><h2 style={{margin:'3px 0 0',fontSize:25,color:C.ink}}>National Intelligence Center</h2><div style={{marginTop:3,fontSize:12.5,color:C.soft}}>One portfolio view across risk, bottlenecks, evidence operations, source health and governed intelligence.</div></div><div style={{display:'flex',gap:8}}><button onClick={exportCsv} style={{display:'inline-flex',gap:7,alignItems:'center',border:`1px solid ${C.border}`,borderRadius:7,padding:'8px 12px',background:'#fff',color:C.ink,fontWeight:600,cursor:'pointer'}}><Download size={14}/>Export queue</button><button onClick={refresh} disabled={loading} style={{display:'inline-flex',gap:7,alignItems:'center',border:0,borderRadius:7,padding:'8px 12px',background:C.primary,color:'#fff',fontWeight:600,cursor:'pointer'}}><RefreshCw size={14}/>Refresh</button></div></div>
  {error&&<Card style={{padding:11,background:C.highTint,color:C.high,fontSize:12}}>{error}</Card>}
  <div style={{display:'grid',gridTemplateColumns:'repeat(4,minmax(0,1fr))',gap:10}}><Metric label="Authorised projects" value={data?.summary?.projects??'—'} icon={Target}/><Metric label="High-risk projects" value={data?.summary?.highRisk??'—'} icon={AlertTriangle}/><Metric label="Open alerts" value={data?.summary?.openAlerts??'—'} icon={Activity}/><Metric label="Completed" value={data?`${data.summary.completionPct}%`:'—'} icon={TrendingUp}/></div>
  <div style={{display:'grid',gridTemplateColumns:'1.25fr 1fr',gap:14}}>
   <Card style={{padding:16}}><div style={{fontSize:11,color:C.faint,textTransform:'uppercase'}}>Intervention queue</div><div style={{marginTop:3,fontSize:17,fontWeight:750,color:C.ink}}>Where officer attention is concentrated</div><div style={{marginTop:11,display:'flex',flexDirection:'column',gap:7}}>{top.slice(0,10).map((x,i)=><div key={x.projectId} style={{display:'grid',gridTemplateColumns:'28px 1.5fr .55fr 1.5fr',gap:10,alignItems:'center',padding:'9px 10px',border:`1px solid ${C.border}`,borderRadius:8,cursor:onOpenProject?'pointer':'default'}} onClick={()=>onOpenProject?.(x.projectId)}><div style={{fontSize:11,color:C.faint}}>#{i+1}</div><div><div style={{fontWeight:700,fontSize:12.5,color:C.ink}}>{x.projectName}</div><div style={{fontSize:10.5,color:C.faint}}>{x.state} · {x.district}</div></div><div style={{fontSize:16,fontWeight:800,color:x.band==='high'?C.high:x.band==='medium'?C.med:C.primary}}>{x.risk}</div><div style={{fontSize:11.5,color:C.soft}}>{x.recommendedAction}</div></div>)}</div>{!top.length&&!loading&&<div style={{padding:20,textAlign:'center',color:C.faint,fontSize:12}}>No intervention candidates in the authorised scope.</div>}</Card>
   <Card style={{padding:16}}><div style={{fontSize:11,color:C.faint,textTransform:'uppercase'}}>Governance</div><div style={{marginTop:3,fontSize:17,fontWeight:750,color:C.ink}}>Intelligence trust state</div><div style={{marginTop:13,display:'flex',flexDirection:'column',gap:10}}><Row label="Production promotion" value={data?.governance?.productionPromotionAllowed?'ALLOWED':'BLOCKED'} good={data?.governance?.productionPromotionAllowed}/><Row label="Governance gate" value={data?.governance?.gateStatus||'—'}/><Row label="Drift" value={data?.governance?.driftStatus||'NOT_AVAILABLE'}/><Row label="Calibration" value={data?.governance?.calibrationError??'NOT_AVAILABLE'}/><Row label="OOD rate" value={data?.governance?.oodRate??'NOT_AVAILABLE'}/><div style={{padding:10,borderRadius:8,background:C.medTint,color:C.med,fontSize:11.5,lineHeight:1.45}}>{data?.trust?.message}</div></div></Card>
  </div>
  <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:14}}>
   <Card style={{padding:16}}><div style={{display:'flex',gap:8,alignItems:'center'}}><BarChart3 size={15} color={C.primary}/><div><div style={{fontSize:11,color:C.faint,textTransform:'uppercase'}}>Stage pressure</div><div style={{fontSize:16,fontWeight:750,color:C.ink}}>Bottleneck distribution</div></div></div><div style={{marginTop:12,display:'flex',flexDirection:'column',gap:8}}>{(data?.stageBottlenecks||[]).slice(0,8).map(s=><button type="button" key={s.stage} onClick={()=>setSelectedStage(s)} style={{display:'block',width:'100%',textAlign:'left',border:`1px solid ${selectedStage?.stage===s.stage?C.primary:C.border}`,background:selectedStage?.stage===s.stage?C.tint:'#fff',borderRadius:8,padding:'8px 9px',cursor:'pointer'}}><div style={{display:'flex',justifyContent:'space-between',fontSize:11.5}}><span>{s.stage}</span><b>{s.avgRisk}/100</b></div><div style={{height:7,background:'#EEF0EA',borderRadius:9,marginTop:4}}><div style={{height:'100%',width:`${Math.min(100,s.avgRisk)}%`,background:s.avgRisk>=65?C.high:s.avgRisk>=40?C.med:C.primary,borderRadius:9}}/></div><div style={{fontSize:10,color:C.faint,marginTop:2}}>{s.projects} projects · {s.highPct}% high-risk · {s.avgDelayDays} avg delay days</div></button>)} {selectedStage&&<div style={{marginTop:9,padding:10,borderRadius:8,background:C.tint,fontSize:11,color:C.soft}}><b style={{color:C.ink}}>{selectedStage.stage}</b> · {selectedStage.projects} projects · average risk {selectedStage.avgRisk}/100 · {selectedStage.highPct}% high-risk · average delay {selectedStage.avgDelayDays} days.</div>}</div></Card>
   <Card style={{padding:16}}><div style={{display:'flex',gap:8,alignItems:'center'}}><Database size={15} color={C.primary}/><div><div style={{fontSize:11,color:C.faint,textTransform:'uppercase'}}>Source health</div><div style={{fontSize:16,fontWeight:750,color:C.ink}}>Authorized/public connector status</div></div></div><div style={{marginTop:12,display:'flex',flexDirection:'column',gap:7}}>{(data?.sourceHealth||[]).map(s=><div key={s.id} style={{display:'flex',justifyContent:'space-between',gap:10,padding:'8px 9px',border:`1px solid ${C.border}`,borderRadius:7}}><div><div style={{fontSize:12,fontWeight:650,color:C.ink}}>{s.name}</div><div style={{fontSize:10,color:C.faint}}>{s.owner} · {s.accessMode}</div></div><div style={{fontSize:10.5,fontWeight:700,color:s.health==='healthy'?C.primary:s.health==='error'?C.high:C.med}}>{s.health}</div></div>)}</div></Card>
  </div>
  <Card style={{padding:12,display:'flex',gap:8,alignItems:'center',fontSize:11.5,color:C.soft}}><ShieldCheck size={15} color={C.primary}/><span>This center consolidates existing persistent intelligence; it does not create a second source of truth. Predictions remain governed candidate intelligence until authorised historical outcome data passes the existing temporal, leakage, calibration, OOD and approval gates.</span></Card>
 </div>
}
function Row({label,value,good}){return <div style={{display:'flex',justifyContent:'space-between',gap:10,fontSize:12}}><span style={{color:C.soft}}>{label}</span><b style={{color:good===true?C.primary:good===false?C.high:C.ink}}>{value}</b></div>}
