import React,{useEffect,useMemo,useState} from 'react';
import {Activity,AlertTriangle,ArrowRight,BarChart3,BrainCircuit,CheckCircle2,Clock3,Database,FlaskConical,RefreshCw,ShieldCheck,Sparkles,Target,TriangleAlert} from 'lucide-react';
import {BarChart,Bar,CartesianGrid,LineChart,Line,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';

const C={bg:'#F4F5F1',surface:'#FFFFFF',sunk:'#EEF0EA',border:'#DBDFD4',ink:'#1B231C',soft:'#586055',faint:'#8A9184',primary:'#2F5C48',inkFaint:'#8A9184',primaryDark:'#1E3E30',gold:'#8A6A32',goldTint:'#F3ECDB',high:'#AC2B22',highTint:'#F8E6E3',med:'#95600A',medTint:'#F7EDD9'};
const FONT="'IBM Plex Sans','Inter',system-ui,sans-serif";
const HEAD="'Source Serif 4',Georgia,'Times New Roman',serif";
const tone=s=>s>=70?[C.high,C.highTint]:s>=55?[C.med,C.medTint]:[C.primary,'#E4EDE6'];
function Card({children,style={},className=''}){return <div className={`bd-card ${className}`} style={{background:C.surface,border:`1px solid ${C.border}`,borderRadius:12,...style}}>{children}</div>}
function Badge({children,status='neutral'}){const m=status==='ready'?{bg:'#E4EDE6',fg:C.primary}:status==='blocked'?{bg:C.goldTint,fg:C.gold}:status==='review'?{bg:C.medTint,fg:C.med}:{bg:C.sunk,fg:C.soft};return <span style={{display:'inline-flex',alignItems:'center',gap:5,padding:'4px 8px',borderRadius:999,background:m.bg,color:m.fg,fontSize:10.5,fontWeight:800,letterSpacing:.25}}>{children}</span>}
function Metric({icon:Icon,label,value,sub}){return <Card style={{padding:15}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><span style={{fontSize:11,color:C.faint}}>{label}</span><Icon size={16} color={C.primary}/></div><div style={{fontFamily:HEAD,fontSize:28,fontWeight:650,color:C.ink,marginTop:5}}>{value}</div>{sub&&<div style={{fontSize:10.5,color:C.faint,marginTop:2}}>{sub}</div>}</Card>}
export default function PredictiveLabPage({onOpenProject,canAdmin=false}){
 const [data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[building,setBuilding]=useState(false),[datasetBuilding,setDatasetBuilding]=useState(false),[message,setMessage]=useState(''),[selected,setSelected]=useState(null),[selectedChart,setSelectedChart]=useState(null);
 const load=async()=>{setLoading(true);setError('');try{const r=await fetch('/api/ml/lab',{credentials:'include'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Predictive lab unavailable.');setData(j);}catch(e){setError(e.message||'Predictive lab unavailable.');}finally{setLoading(false);}};
 useEffect(()=>{load();},[]);
 const buildTemporal=async()=>{if(!canAdmin){setError('Administrator governance permission is required to build the temporal research dataset.');return;}setDatasetBuilding(true);setError('');setMessage('Building a point-in-time temporal research dataset from authorised repository records…');try{const r=await fetch('/api/predictive/dataset/build',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:'{}'});const j=await r.json();if(!r.ok)throw new Error(j.error||'Temporal dataset build failed safely.');setMessage(`Temporal dataset ${j.dataset?.status||'created'}: ${j.dataset?.exampleCount||0} examples, ${j.dataset?.observedLabelCount||0} observed labels. Production ML remains blocked.`);await load();}catch(e){setError(e.message||'Temporal dataset build failed safely.');setMessage('');}finally{setDatasetBuilding(false);}};
 const build=async()=>{if(!canAdmin){setError('Administrator governance permission is required to build the research artifact.');return;}setBuilding(true);setError('');setMessage('Checking reviewed dataset and governance gates…');try{const r=await fetch('/api/ml/lab/build-artifact',{method:'POST',credentials:'include'});const j=await r.json();if(r.status===409){setMessage(j.error||'Research artifact build safely blocked: reviewed training data is required.');return;}if(!r.ok)throw new Error(j.error||'Artifact build failed safely.');setMessage('Research candidate artifact created. Production promotion remains blocked.');await load();}catch(e){setError(e.message||'Artifact build failed safely.');setMessage('');}finally{setBuilding(false);}};
 const chart=useMemo(()=>data?.ranked?.slice(0,10).map(x=>({name:String(x.projectName||'').slice(0,17),signal:Number(x.signalPct||0)}))||[],[data]);
 if(loading)return <div style={{fontFamily:FONT,color:C.soft,padding:30}}>Preparing predictive intelligence lab…</div>;
 if(error)return <Card style={{padding:16,background:C.highTint,color:C.high,fontFamily:FONT}}><AlertTriangle size={15}/> {error}</Card>;
 return <div style={{fontFamily:FONT,display:'flex',flexDirection:'column',gap:14}}>
  <div className="bd-hero bd-reveal" style={{padding:'20px 22px',background:C.primaryDark,borderRadius:14,color:'#fff',position:'relative',overflow:'hidden'}}>
   <div className="bd-orb"/><div style={{position:'relative',zIndex:1,display:'flex',justifyContent:'space-between',gap:18,alignItems:'flex-start',flexWrap:'wrap'}}>
    <div><div style={{fontSize:10.5,textTransform:'uppercase',letterSpacing:1,color:'#ffffff99'}}>BhoomiDrishti intelligence laboratory</div><h1 style={{fontFamily:HEAD,fontSize:28,fontWeight:650,margin:'5px 0 3px'}}>Predictive Intelligence Lab</h1><div style={{fontSize:12.5,color:'#ffffffb8',maxWidth:760,lineHeight:1.5}}>A controlled path from authorised historical evidence to point-in-time features, temporal evaluation, calibrated probabilities and explainable project intelligence.</div></div>
    <div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button onClick={load} disabled={loading||building||datasetBuilding} className="bd-action" style={{background:'#ffffff16',color:'#fff',border:'1px solid #ffffff2e'}}><RefreshCw size={14}/>{loading?'Loading':'Refresh'}</button><button onClick={buildTemporal} disabled={!canAdmin||datasetBuilding||building} title={canAdmin?'Build a point-in-time research dataset':'Administrator governance permission required'} className="bd-action" style={{background:'#ffffff16',color:'#fff',border:'1px solid #ffffff2e',opacity:canAdmin?1:.55}}><Database size={14}/>{datasetBuilding?'Preparing…':canAdmin?'Build temporal dataset':'Temporal dataset · Admin'}</button><button onClick={build} disabled={!canAdmin||building||datasetBuilding||!data?.pipeline?.find(s=>s.id==='temporal')?.detail?.includes('reviewed')} title={canAdmin?'Build the governed research candidate artifact':'Administrator governance permission required'} className="bd-action" style={{background:'#fff',color:C.primaryDark,border:0,opacity:canAdmin&&data?.pipeline?.find(s=>s.id==='temporal')?.detail?.includes('reviewed')?1:.55}}><FlaskConical size={14}/>{building?'Building…':canAdmin?'Build research artifact':'Research artifact · Admin'}</button></div>
   </div>
  </div>
  {!canAdmin&&<Card className="bd-reveal" style={{padding:11,background:C.goldTint,border:`1px solid ${C.gold}33`,color:C.soft,fontSize:11.5}}><ShieldCheck size={14} color={C.gold}/> Research-build actions are administrator-governed. You can inspect the live candidate intelligence here; no permission error is raised for read-only analysis.</Card>}
  {message&&<Card className="bd-reveal" style={{padding:11,background:'#E4EDE6',color:C.primary,fontSize:11.5}}><CheckCircle2 size={14}/> {message}</Card>}
  {error&&<Card style={{padding:11,background:C.highTint,color:C.high,fontSize:11.5}}><TriangleAlert size={14}/> {error}</Card>}
  <Card className="bd-reveal" style={{padding:12,background:C.goldTint,border:`1px solid ${C.gold}33`}}><div style={{display:'flex',gap:10,alignItems:'flex-start'}}><ShieldCheck size={16} color={C.gold}/><div style={{fontSize:11.5,color:C.soft,lineHeight:1.45}}><b style={{color:C.ink}}>Research governance:</b> candidate signals are live from the authorised project portfolio. A calibrated research artifact requires reviewed historical outcome data. The temporal-dataset action prepares point-in-time examples for review; it never promotes data or models to production.</div></div></Card>
  <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-3">
   <><Metric icon={Database} label="Projects in scope" value={data.projectCount} sub={data.activeProjectCount + " ongoing"} /><Metric icon={Target} label="High exposure signals" value={data.distribution.high} sub={data.distribution.watch + " in watch band"} /><Metric icon={BrainCircuit} label="Research artifact" value={data.artifact ? "Available" : "Not built"} sub={data.artifact?.version || "Awaiting reviewed data"} /><Metric icon={ShieldCheck} label="Production status" value="BLOCKED" sub="Human governance required" /></>
  </div>
  <Card style={{padding:16}} className="bd-reveal"><div style={{display:'flex',justifyContent:'space-between',alignItems:'flex-end',gap:10,marginBottom:13}}><div><div style={{fontSize:10.5,textTransform:'uppercase',letterSpacing:.7,color:C.faint}}>Model journey</div><div style={{fontFamily:HEAD,fontSize:21,fontWeight:650,color:C.ink}}>From evidence to governed prediction</div></div><Badge status="blocked">SAFE BY DEFAULT</Badge></div>
   <div className="bd-pipeline">{data.pipeline.map((s,i)=><React.Fragment key={s.id}><div className={`bd-step ${s.status==='READY'?'ready':s.status==='REVIEW'?'review':'blocked'}`}><div className="bd-step-icon">{s.status==='READY'?<CheckCircle2 size={15}/>:s.status==='REVIEW'?<Activity size={15}/>:<ShieldCheck size={15}/>}</div><div style={{fontSize:11.5,fontWeight:800,color:C.ink}}>{s.label}</div><Badge status={s.status==='READY'?'ready':s.status==='REVIEW'?'review':'blocked'}>{s.status}</Badge><div style={{fontSize:10.5,color:C.faint,lineHeight:1.35}}>{s.detail}</div></div>{i<data.pipeline.length-1&&<ArrowRight className="bd-pipe-arrow" size={15} color={C.inkFaint}/>}</React.Fragment>)}</div>
  </Card>
  {selectedChart&&<Card style={{padding:12,background:C.sunk}}><div style={{display:"flex",justifyContent:"space-between",gap:10,alignItems:"center"}}><div><b style={{fontSize:12.5,color:C.ink}}>{selectedChart.projectName}</b><div style={{fontSize:10.5,color:C.faint,marginTop:2}}>{selectedChart.district}, {selectedChart.state} · candidate signal {selectedChart.signalPct}% · expected additional delay {selectedChart.expectedAdditionalDays}d</div></div><div style={{display:"flex",gap:7}}><button className="bd-action" onClick={()=>onOpenProject(selectedChart.projectId)} style={{background:C.primary,color:"#fff",border:0}}>Open project <ArrowRight size={13}/></button><button className="bd-action" onClick={()=>setSelectedChart(null)}>Clear</button></div></div></Card>}
  <div className="grid grid-cols-1 xl:grid-cols-2 gap-4">
   <Card style={{padding:16}} className="bd-reveal"><div style={{fontSize:10.5,textTransform:'uppercase',color:C.faint,letterSpacing:.7}}>Current candidate signals</div><div style={{fontFamily:HEAD,fontSize:20,fontWeight:650,color:C.ink,margin:'3px 0 10px'}}>Project exposure landscape</div><div style={{height:250}}><ResponsiveContainer width="100%" height="100%"><BarChart data={chart} margin={{top:8,right:8,left:-20,bottom:0}}><CartesianGrid stroke={C.border} strokeDasharray="3 3"/><XAxis dataKey="name" tick={{fontFamily:FONT,fontSize:9,fill:C.faint}} interval={0} angle={-20} textAnchor="end" height={55} axisLine={{stroke:C.border}} tickLine={false}/><YAxis domain={[0,100]} tick={{fontFamily:FONT,fontSize:9,fill:C.faint}} width={28} axisLine={false} tickLine={false}/><Tooltip contentStyle={{fontFamily:FONT,fontSize:11,border:`1px solid ${C.border}`,borderRadius:8}} formatter={v=>[`${v}%`,'Candidate signal']}/><Bar dataKey="signal" radius={[5,5,0,0]} fill={C.primary} maxBarSize={30} onClick={(entry)=>{const hit=data?.ranked?.find(x=>String(x.projectName||'').slice(0,17)===String(entry?.payload?.name||''));setSelectedChart(hit||null);}}/></BarChart></ResponsiveContainer></div></Card>
   <Card style={{padding:16}} className="bd-reveal"><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><div style={{fontSize:10.5,textTransform:'uppercase',color:C.faint,letterSpacing:.7}}>Attention queue</div><div style={{fontFamily:HEAD,fontSize:20,fontWeight:650,color:C.ink}}>Inspect a project</div></div><Sparkles size={18} color={C.gold}/></div><div style={{display:'flex',flexDirection:'column',gap:7,marginTop:11}}>{data.ranked.slice(0,8).map((p,i)=>{const [col,bg]=tone(p.signalPct);return <button key={p.projectId} onClick={()=>setSelected(p)} className="bd-row" style={{textAlign:'left',background:bg,border:`1px solid ${col}22`}}><div style={{display:'flex',alignItems:'center',gap:10}}><div style={{width:24,height:24,borderRadius:7,background:'#fff',display:'grid',placeItems:'center',fontSize:10,fontWeight:800,color:col}}>{i+1}</div><div style={{flex:1,minWidth:0}}><div style={{fontSize:11.5,fontWeight:800,color:C.ink,whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis'}}>{p.projectName}</div><div style={{fontSize:9.8,color:C.faint}}>{p.district}, {p.state} · {p.stage}</div></div><div style={{fontFamily:HEAD,fontSize:21,fontWeight:700,color:col}}>{p.signalPct}</div><ArrowRight size={14} color={C.faint}/></div></button>})}</div></Card>
  </div>
  <Card style={{padding:16}} className="bd-reveal"><div style={{display:'flex',justifyContent:'space-between',gap:10,alignItems:'center'}}><div><div style={{fontSize:10.5,textTransform:'uppercase',color:C.faint,letterSpacing:.7}}>Governance boundary</div><div style={{fontFamily:HEAD,fontSize:20,fontWeight:650,color:C.ink}}>What the system will and will not claim</div></div><ShieldCheck size={19} color={C.primary}/></div><div className="grid grid-cols-1 md:grid-cols-3 gap-3" style={{marginTop:12}}><Governance title="Prediction" text="Candidate signals can support investigation; calibrated probability claims require validated historical outcomes."/><Governance title="Evidence" text="Every production feature must remain traceable to a point-in-time source snapshot or verified project fact."/><Governance title="Action" text="Recommendations remain decision support. Officer review and applicable workflow rules remain authoritative."/></div></Card>
  {selected&&<div className="bd-modal-backdrop" onClick={()=>setSelected(null)}><div className="bd-modal" onClick={e=>e.stopPropagation()}><div style={{display:'flex',justifyContent:'space-between',gap:12}}><div><div style={{fontSize:10,textTransform:'uppercase',color:C.faint}}>Project intelligence</div><div style={{fontFamily:HEAD,fontSize:24,fontWeight:650,color:C.ink}}>{selected.projectName}</div></div><button className="bd-action" onClick={()=>setSelected(null)}>Close</button></div><div className="grid grid-cols-2 gap-3" style={{marginTop:15}}><Metric icon={Target} label="Candidate signal" value={`${selected.signalPct}%`} sub="Not calibrated"/><Metric icon={Clock3} label="Expected additional" value={`${selected.expectedAdditionalDays}d`} sub="Candidate estimate"/></div><div style={{marginTop:13,padding:12,borderRadius:10,background:C.sunk,fontSize:11.5,color:C.soft,lineHeight:1.5}}><b style={{color:C.ink}}>Primary driver:</b> {selected.topDriver?.label||'Not available'} · <b style={{color:C.ink}}>Applicability:</b> {selected.ood}.<br/>The detailed project page contains evidence, actions, legal workflow and the existing what-if simulator.</div><div style={{display:'flex',justifyContent:'flex-end',gap:8,marginTop:14}}><button className="bd-action" onClick={()=>{onOpenProject(selected.projectId);setSelected(null);}} style={{background:C.primary,color:'#fff',border:0}}>Open project <ArrowRight size={14}/></button></div></div></div>}
 </div>
}
function Governance({title,text}){return <div style={{padding:12,border:`1px solid ${C.border}`,borderRadius:10,background:C.surface}}><div style={{fontSize:12,fontWeight:800,color:C.ink}}>{title}</div><div style={{fontSize:10.8,color:C.soft,lineHeight:1.45,marginTop:4}}>{text}</div></div>}
