import React,{useEffect,useMemo,useState} from 'react';
import {ShieldCheck,RefreshCw,Database,BrainCircuit,Activity,LockKeyhole,CheckCircle2,AlertTriangle,Server,HardDrive} from 'lucide-react';
const C={surface:'#fff',border:'#DBDFD4',ink:'#1B231C',soft:'#586055',faint:'#8A9184',primary:'#2F5C48',tint:'#E4EDE6',high:'#AC2B22',highTint:'#F8E6E3',med:'#95600A',medTint:'#F7EDD9'};
const Card=({children,style={},className=''})=><div className={`bd-card ${className}`} style={{background:C.surface,border:`1px solid ${C.border}`,borderRadius:10,...style}}>{children}</div>;
const Metric=({label,value,sub,iconComponent,title})=><Card title={title||label} style={{padding:14,minWidth:0}}><div style={{display:'flex',justifyContent:'space-between',gap:10,alignItems:'flex-start'}}><div className="bd-safe-text"><div style={{fontSize:10.5,color:C.faint,textTransform:'uppercase',letterSpacing:.6,lineHeight:1.25}}>{label}</div><div style={{fontSize:27,fontWeight:750,color:C.ink,marginTop:4,lineHeight:1.05}}>{value}</div><div style={{fontSize:11.5,color:C.soft,marginTop:4,lineHeight:1.35}}>{sub}</div></div>{iconComponent&&React.createElement(iconComponent,{size:19,color:C.primary,style:{flex:'0 0 auto'}})}</div></Card>;
function StatusBadge({kind='neutral',children}){return <span className={`bd-status-badge ${kind}`}>{children}</span>}
function connectorState(connector){
 const latest=connector?.latest;
 if(!latest) return {kind:'warn',label:'NOT SYNCED',detail:'No snapshot captured'};
 if(latest.ok) return {kind:'ok',label:'SNAPSHOT OK',detail:`${new Date(latest.fetchedAt||latest.createdAt).toLocaleString()}`};
 return {kind:'bad',label:'SYNC FAILED',detail:latest.errorMessage||'Last snapshot failed'};
}
export default function ProductionReadinessPage(){
 const [data,setData]=useState(null),[gates,setGates]=useState(null),[connectors,setConnectors]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const load=async()=>{setLoading(true);setError('');try{const [a,b,c]=await Promise.all([fetch('/api/system/readiness',{credentials:'include'}),fetch('/api/ml/gates',{credentials:'include'}),fetch('/api/source-connectors/catalog',{credentials:'include'})]);const [aj,bj,cj]=await Promise.all([a.json(),b.json(),c.json()]);if(!a.ok)throw new Error(aj.error||'System readiness unavailable.');setData(aj);setGates(bj);setConnectors(cj.connectors||[]);}catch(e){setError(e.message||'Production readiness unavailable.')}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const snapshotCount=useMemo(()=>connectors.filter(x=>x.latest?.ok).length,[connectors]);
 const blocked=Boolean(gates?.gate?.status==='BLOCKED'||data?.intelligence?.productionGate==='BLOCKED');
 return <div className="bd-page" style={{fontFamily:"'IBM Plex Sans','Inter',system-ui,sans-serif",display:'flex',flexDirection:'column',gap:14}}>
  <div className="bd-page-header"><div className="bd-page-header-copy"><div style={{fontSize:10.5,color:C.faint,textTransform:'uppercase',letterSpacing:.7}}>Production readiness</div><h2 className="bd-page-title">System Readiness Center</h2><div className="bd-page-subtitle">A factual view of what is operational today, what is governed, and what still requires authorised data or infrastructure.</div></div><div className="bd-page-actions"><button className="bd-small-action primary" onClick={load} disabled={loading}><RefreshCw size={14}/>{loading?'Refreshing…':'Refresh'}</button></div></div>
  {error&&<Card style={{padding:12,background:C.highTint,color:C.high,fontSize:12,lineHeight:1.45}}>{error}</Card>}
  <div className="bd-responsive-kpis">
   <Metric label="Authorised projects" value={data?.scope?.projects??'—'} sub={`${data?.scope?.ongoing??0} ongoing`} iconComponent={Database} title="Authorised projects in the current user scope."/>
   <Metric label="Open alerts" value={data?.operations?.openAlerts??'—'} sub={`${data?.operations?.alerts??0} total alert records`} iconComponent={Activity} title="Unresolved operational alerts in the current scope."/>
   <Metric label="Verified source snapshots" value={snapshotCount} sub={`${connectors.length} connectors in catalog`} iconComponent={Server} title="Connectors with a successful public-source snapshot; this does not mean authoritative government project-record access."/>
   <Metric label="Production ML model" value={blocked?'Blocked':'Eligible'} sub={blocked?'Governance/data gate still open':'Governance gate satisfied'} iconComponent={BrainCircuit} title="Production ML promotion status, separate from application availability."/>
  </div>
  <div className="bd-responsive-two">
   <Card style={{padding:16}}><div style={{display:'flex',alignItems:'center',gap:9}}><ShieldCheck size={19} color={C.primary}/><div className="bd-safe-text"><div style={{fontSize:10.5,color:C.faint,textTransform:'uppercase'}}>Deployment truth</div><div style={{fontSize:18,fontWeight:750,color:C.ink}}>What can be trusted today?</div></div></div><div className="bd-trust-grid">
    {[['Persistent data store',true,'Shared store is readable and writable'],['Audit trail',data?.architecture?.auditTrail,'Application audit trail is enabled'],['Temporal controls',data?.architecture?.temporalControls,'As-of and leakage controls are present'],['Evidence-grounded AI',data?.architecture?.aiEvidenceGrounded,'AI responses use the evidence layer'],['Automatic project bootstrap',Boolean(data?.architecture?.automaticProjectBootstrap),'New projects receive the lifecycle foundation'],['Government integrations',false,'Require authorised access contracts']].map(([label,ok,sub])=><div key={label} style={{border:`1px solid ${C.border}`,borderRadius:8,padding:11,background:'#FAFBF8',minWidth:0}}><div style={{display:'flex',alignItems:'flex-start',gap:7,fontWeight:700,fontSize:12.5,color:C.ink,lineHeight:1.3}}>{ok?<CheckCircle2 size={15} color={C.primary}/>:<AlertTriangle size={15} color={C.med}/>}<span className="bd-safe-text">{label}</span></div><div style={{fontSize:11,color:C.soft,marginTop:5,lineHeight:1.45}}>{sub}</div></div>)}
   </div></Card>
   <Card style={{padding:16}}><div style={{display:'flex',alignItems:'center',gap:9}}><LockKeyhole size={18} color={blocked?C.med:C.primary}/><div className="bd-safe-text"><div style={{fontSize:10.5,color:C.faint,textTransform:'uppercase'}}>ML governance</div><div style={{fontSize:19,fontWeight:750,color:blocked?C.med:C.primary}}>{blocked?'Production ML promotion blocked':'Production ML promotion eligible'}</div></div></div><div style={{marginTop:14,fontSize:12.5,color:C.soft,lineHeight:1.55}}>{blocked?'The candidate predictive layer remains decision support. Authorised real historical outcomes, calibration, OOD checks and governance approval are required before production promotion.':'The current governance gate is satisfied.'}</div><div style={{marginTop:14,padding:10,borderRadius:8,background:blocked?C.medTint:C.tint,fontSize:11.5,color:blocked?C.med:C.primary,overflowWrap:'anywhere'}}>{gates?.gate?.status||data?.intelligence?.productionGate||'Checking gate…'}</div></Card>
  </div>
  <Card style={{padding:16}}><div style={{display:'flex',alignItems:'center',gap:9}}><HardDrive size={18} color={C.primary}/><div><div style={{fontSize:10.5,color:C.faint,textTransform:'uppercase'}}>Operational limits</div><div style={{fontSize:18,fontWeight:750,color:C.ink}}>What still needs real-world enablement</div></div></div><div style={{display:'grid',gap:8,marginTop:12}}>{(data?.limitations||['Government integrations require authorised contracts.','Production ML requires validated historical outcome data.']).map(x=><div key={x} style={{padding:'10px 12px',border:`1px solid ${C.border}`,borderRadius:8,fontSize:12,color:C.soft,lineHeight:1.45,overflowWrap:'anywhere'}}>{x}</div>)}</div></Card>
  <Card style={{padding:16}}><div style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:10,flexWrap:'wrap'}}><div><div style={{fontSize:10.5,color:C.faint,textTransform:'uppercase'}}>Source readiness</div><div style={{fontSize:17,fontWeight:750,color:C.ink}}>Current connector evidence</div></div><StatusBadge kind={snapshotCount?'ok':'warn'}>{snapshotCount}/{connectors.length} snapshots available</StatusBadge></div><div style={{display:'grid',gap:7,marginTop:12}}>{connectors.slice(0,6).map(c=>{const s=connectorState(c);return <div key={c.id} style={{display:'grid',gridTemplateColumns:'minmax(0,1fr) auto',gap:10,alignItems:'center',padding:'9px 10px',border:`1px solid ${C.border}`,borderRadius:8}}><div className="bd-safe-text"><div style={{fontSize:11.5,fontWeight:700,color:C.ink}}>{c.name}</div><div className="bd-inline-note">{c.owner} · {c.scope}</div></div><div style={{textAlign:'right'}}><StatusBadge kind={s.kind}>{s.label}</StatusBadge><div className="bd-inline-note" style={{marginTop:3}}>{s.detail}</div></div></div>})}</div><div className="bd-inline-note" style={{marginTop:10}}>Public-source snapshots are evidence for monitoring/discovery only; they are not automatically authoritative project records.</div></Card>
 </div>
}
