'use strict';
const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
const {spawnSync}=require('node:child_process');
const root=path.resolve(__dirname,'..');
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'bhoomidrishti-u54-gis-'));
const env={...process.env,BHOOMI_STORAGE_MODE:'shared',BHOOMI_PERSISTENT_ROOT:tmp};
const script=`import {getProject,close} from './backend/db.js';
const p=getProject('P-001');
console.log('SEED',p.district,p.latitude,p.longitude,p.locationPrecision,p.locationAuthority);
close();`;
let r=spawnSync(process.execPath,['--input-type=module','-e',script],{cwd:root,env,encoding:'utf8'});
if(r.status!==0) throw new Error(r.stderr||r.stdout||'gis seed process failed');
if(!/SEED Salem 11\.6643 78\.146 DISTRICT_CENTROID DEMO_APPROXIMATE/.test(r.stdout)) throw new Error('seed GIS point/provenance mismatch');
const db=path.join(tmp,'bhoomidrishti.sqlite');
const py=`import sqlite3; p=r'''${db}'''; c=sqlite3.connect(p); c.execute("UPDATE projects SET latitude=26.8467,longitude=80.9462,location_source='DEMO_DISTRICT_CENTROID',location_precision='DISTRICT_CENTROID' WHERE id='P-001'"); c.commit(); c.close()`;
r=spawnSync('python',['-c',py],{cwd:root,env,encoding:'utf8'});
if(r.status!==0) throw new Error(r.stderr||'python GIS mutation failed');
r=spawnSync(process.execPath,['--input-type=module','-e',script],{cwd:root,env,encoding:'utf8'});
if(r.status!==0) throw new Error(r.stderr||r.stdout||'gis repair process failed');
if(!/SEED Salem 11\.6643 78\.146 DISTRICT_CENTROID DEMO_APPROXIMATE/.test(r.stdout)) throw new Error('synthetic GIS correction failed');
fs.rmSync(tmp,{recursive:true,force:true});
console.log('GIS correction E2E smoke PASSED');
